# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/I2S.xdc

# Block Designs: bd/ClockGeneration/ClockGeneration.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ClockGeneration || ORIG_REF_NAME==ClockGeneration} -quiet] -quiet

# IP: bd/ClockGeneration/ip/ClockGeneration_clk_wiz_0_0/ClockGeneration_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ClockGeneration_clk_wiz_0_0 || ORIG_REF_NAME==ClockGeneration_clk_wiz_0_0} -quiet] -quiet

# Block Designs: bd/DataROM/DataROM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataROM || ORIG_REF_NAME==DataROM} -quiet] -quiet

# IP: bd/DataROM/ip/DataROM_AXI4S_ROM_0_1/DataROM_AXI4S_ROM_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataROM_AXI4S_ROM_0_1 || ORIG_REF_NAME==DataROM_AXI4S_ROM_0_1} -quiet] -quiet

# XDC: bd/ClockGeneration/ClockGeneration_ooc.xdc

# XDC: bd/DataROM/DataROM_ooc.xdc
