webtalk_init -webtalk_dir /home/daniel/Schreibtisch/Git/VHDL/SevenSegment/SevenSegment.sim/sim_1/behav/xsim/xsim.dir/Testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 16 22:17:59 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2348494" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210727995_1777512417_210616669_940" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "044a8178ed48539893e57acde79755c1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "672aec34551548c385399ead1d902fb6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3999.668 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "10.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124136_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2151919305 -regid "210727995_1777512417_210616669_940" -xml /home/daniel/Schreibtisch/Git/VHDL/SevenSegment/SevenSegment.sim/sim_1/behav/xsim/xsim.dir/Testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/daniel/Schreibtisch/Git/VHDL/SevenSegment/SevenSegment.sim/sim_1/behav/xsim/xsim.dir/Testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/daniel/Schreibtisch/Git/VHDL/SevenSegment/SevenSegment.sim/sim_1/behav/xsim/xsim.dir/Testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
